name: Copy Environment Files
description: "Copies environment files based on branch"
runs:
  using: "composite"
  steps:
    - name: Copy Environment Files
      shell: bash
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          cp ./.github/workflows/main.env ./ui-desktop/.env
        elif [[ "${GITHUB_REF}" == "refs/heads/test" ]]; then
          cp ./.github/workflows/test.env ./ui-desktop/.env
        else
          cp ./.github/workflows/test.env ./ui-desktop/.env
        fi
