// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/blockchain/allowance": {
            "get": {
                "description": "Get MOR allowance for spender",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get Allowance for MOR",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Spender address",
                        "name": "spender",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.AllowanceRes"
                        }
                    }
                }
            }
        },
        "/blockchain/approve": {
            "post": {
                "description": "Approve MOR allowance for spender",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Approve MOR allowance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Spender address",
                        "name": "spender",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Amount",
                        "name": "amount",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.TxRes"
                        }
                    }
                }
            }
        },
        "/blockchain/balance": {
            "get": {
                "description": "Get ETH and MOR balance of the user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get ETH and MOR balance",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.TokenBalanceRes"
                        }
                    }
                }
            }
        },
        "/blockchain/bids": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bids"
                ],
                "summary": "Creates bid in blockchain",
                "parameters": [
                    {
                        "description": "Bid",
                        "name": "bid",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.CreateBidRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.BidRes"
                        }
                    }
                }
            }
        },
        "/blockchain/bids/{id}": {
            "get": {
                "description": "Get bid from blockchain by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bids"
                ],
                "summary": "Get Bid by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bid ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.BidRes"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bids"
                ],
                "summary": "Delete Bid",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bid ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.TxRes"
                        }
                    }
                }
            }
        },
        "/blockchain/bids/{id}/session": {
            "post": {
                "description": "Full flow to open a session by bidId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Open Session by bidId in blockchain",
                "parameters": [
                    {
                        "description": "Open session",
                        "name": "opensession",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.OpenSessionWithDurationRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Bid ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.OpenSessionRes"
                        }
                    }
                }
            }
        },
        "/blockchain/latestBlock": {
            "get": {
                "description": "Get latest block number from blockchain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get Latest Block",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.BlockRes"
                        }
                    }
                }
            }
        },
        "/blockchain/models": {
            "get": {
                "description": "Get models list from blokchain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Get models list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.ModelsRes"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Creates model in blockchain",
                "parameters": [
                    {
                        "description": "Model",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.CreateModelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.ModelRes"
                        }
                    }
                }
            }
        },
        "/blockchain/models/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "models"
                ],
                "summary": "Deregister Model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.TxRes"
                        }
                    }
                }
            }
        },
        "/blockchain/models/{id}/bids": {
            "get": {
                "description": "Get bids from blockchain by model agent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bids"
                ],
                "summary": "Get Active Bids by Model",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ModelAgent ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.BidsRes"
                        }
                    }
                }
            }
        },
        "/blockchain/models/{id}/bids/rated": {
            "get": {
                "description": "Get rated bids from blockchain by model",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bids"
                ],
                "summary": "Get Rated Bids",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.ScoredBidsRes"
                        }
                    }
                }
            }
        },
        "/blockchain/models/{id}/session": {
            "post": {
                "description": "Full flow to open a session by modelId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Open Session by ModelID in blockchain",
                "parameters": [
                    {
                        "description": "Open session",
                        "name": "opensession",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.OpenSessionWithDurationRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Model ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.OpenSessionRes"
                        }
                    }
                }
            }
        },
        "/blockchain/providers": {
            "get": {
                "description": "Get providers list from blokchain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "providers"
                ],
                "summary": "Get providers list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.ProvidersRes"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "providers"
                ],
                "summary": "Creates or updates provider in blockchain",
                "parameters": [
                    {
                        "description": "Provider",
                        "name": "provider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.CreateProviderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.ProviderRes"
                        }
                    }
                }
            }
        },
        "/blockchain/providers/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "providers"
                ],
                "summary": "Deregister Provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider Address",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.TxRes"
                        }
                    }
                }
            }
        },
        "/blockchain/providers/{id}/bids": {
            "get": {
                "description": "Get bids from blockchain by provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bids"
                ],
                "summary": "Get Bids by Provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.BidsRes"
                        }
                    }
                }
            }
        },
        "/blockchain/providers/{id}/bids/active": {
            "get": {
                "description": "Get bids from blockchain by provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bids"
                ],
                "summary": "Get Bids by Provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.BidsRes"
                        }
                    }
                }
            }
        },
        "/blockchain/send/eth": {
            "post": {
                "description": "Send Eth to address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Send Eth",
                "parameters": [
                    {
                        "description": "Send Eth",
                        "name": "sendeth",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.SendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.TxRes"
                        }
                    }
                }
            }
        },
        "/blockchain/send/mor": {
            "post": {
                "description": "Send Mor to address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Send Mor",
                "parameters": [
                    {
                        "description": "Send Mor",
                        "name": "sendmor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.SendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.TxRes"
                        }
                    }
                }
            }
        },
        "/blockchain/sessions": {
            "get": {
                "description": "Get sessions from blockchain by user or provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Get Sessions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Provider address",
                        "name": "provider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User address",
                        "name": "user",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.SessionsRes"
                        }
                    }
                }
            },
            "post": {
                "description": "Sends transaction in blockchain to open a session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Open Session with Provider in blockchain",
                "parameters": [
                    {
                        "description": "Open session",
                        "name": "opensession",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.OpenSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.OpenSessionRes"
                        }
                    }
                }
            }
        },
        "/blockchain/sessions/budget": {
            "get": {
                "description": "Get todays budget from blockchain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Get Todays Budget",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.BudgetRes"
                        }
                    }
                }
            }
        },
        "/blockchain/sessions/{id}": {
            "get": {
                "description": "Returns session by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Get session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.SessionRes"
                        }
                    }
                }
            }
        },
        "/blockchain/sessions/{id}/close": {
            "post": {
                "description": "Sends transaction in blockchain to close a session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Close Session with Provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.TxRes"
                        }
                    }
                }
            }
        },
        "/blockchain/token/supply": {
            "get": {
                "description": "Get MOR token supply from blockchain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Get Token Supply",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.SupplyRes"
                        }
                    }
                }
            }
        },
        "/blockchain/transactions": {
            "get": {
                "description": "Get MOR and ETH transactions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get Transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.TransactionsRes"
                        }
                    }
                }
            }
        },
        "/config": {
            "get": {
                "description": "Return the current config of proxy router",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "Get Config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.ConfigResponse"
                        }
                    }
                }
            }
        },
        "/files": {
            "get": {
                "description": "Returns opened files",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "Get files",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/system.FD"
                            }
                        }
                    }
                }
            }
        },
        "/healthcheck": {
            "get": {
                "description": "do ping",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "Healthcheck example",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/system.HealthCheckResponse"
                        }
                    }
                }
            }
        },
        "/proxy/sessions/initiate": {
            "post": {
                "description": "sends a handshake to the provider",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Initiate Session with Provider",
                "parameters": [
                    {
                        "description": "Initiate Session",
                        "name": "initiateSession",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxyapi.InitiateSessionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/morrpcmesssage.SessionRes"
                        }
                    }
                }
            }
        },
        "/proxy/sessions/{id}/providerClaim": {
            "post": {
                "description": "Claim provider balance from session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Claim Provider Balance",
                "parameters": [
                    {
                        "description": "Claim",
                        "name": "claim",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/structs.AmountReq"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.TxRes"
                        }
                    }
                }
            }
        },
        "/proxy/sessions/{id}/providerClaimableBalance": {
            "get": {
                "description": "Get provider claimable balance from session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Get Provider Claimable Balance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.BalanceRes"
                        }
                    }
                }
            }
        },
        "/v1/chat/completions": {
            "post": {
                "description": "Send prompt to a local or remote model based on session id in header",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Send Local Or Remote Prompt",
                "parameters": [
                    {
                        "type": "string",
                        "format": "hex32",
                        "description": "Session ID",
                        "name": "session_id",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "format": "hex32",
                        "description": "Model ID",
                        "name": "model_id",
                        "in": "header"
                    },
                    {
                        "description": "Prompt",
                        "name": "prompt",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proxyapi.OpenAiCompletitionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proxyapi.ChatCompletionResponse"
                        }
                    }
                }
            }
        },
        "/v1/models": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chat"
                ],
                "summary": "Get local models",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/aiengine.LocalModel"
                            }
                        }
                    }
                }
            }
        },
        "/wallet": {
            "get": {
                "description": "Get wallet address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Get Wallet",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/walletapi.WalletRes"
                        }
                    }
                }
            },
            "post": {
                "description": "Set wallet private key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Set Wallet",
                "parameters": [
                    {
                        "description": "Private key",
                        "name": "privatekey",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/walletapi.SetupWalletReqBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/walletapi.statusRes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "aiengine.LocalModel": {
            "type": "object",
            "properties": {
                "apiType": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "morrpcmesssage.SessionRes": {
            "type": "object",
            "required": [
                "approval",
                "approvalSig",
                "message",
                "signature",
                "timestamp",
                "user"
            ],
            "properties": {
                "approval": {
                    "type": "string"
                },
                "approvalSig": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "proxyapi.ChatCompletionChoice": {
            "type": "object",
            "properties": {
                "finish_reason": {
                    "description": "FinishReason\nstop: API returned complete message,\nor a message terminated by one of the stop sequences provided via the stop parameter\nlength: Incomplete model output due to max_tokens parameter or token limit\nfunction_call: The model decided to call a function\ncontent_filter: Omitted content due to a flag from our content filters\nnull: API response still in progress or incomplete",
                    "allOf": [
                        {
                            "$ref": "#/definitions/proxyapi.FinishReason"
                        }
                    ]
                },
                "index": {
                    "type": "integer"
                },
                "logprobs": {
                    "$ref": "#/definitions/proxyapi.LogProbs"
                },
                "message": {
                    "$ref": "#/definitions/proxyapi.ChatCompletionMessage"
                }
            }
        },
        "proxyapi.ChatCompletionMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "multiContent": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/proxyapi.ChatMessagePart"
                    }
                },
                "name": {
                    "description": "This property isn't in the official documentation, but it's in\nthe documentation for the official library for python:\n- https://github.com/openai/openai-python/blob/main/chatml.md\n- https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb",
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "tool_call_id": {
                    "description": "For Role=tool prompts this should be set to the ID given in the assistant's prior request to call a tool.",
                    "type": "string"
                }
            }
        },
        "proxyapi.ChatCompletionResponse": {
            "type": "object",
            "properties": {
                "choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/proxyapi.ChatCompletionChoice"
                    }
                },
                "created": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "object": {
                    "type": "string"
                },
                "system_fingerprint": {
                    "type": "string"
                },
                "usage": {
                    "$ref": "#/definitions/proxyapi.Usage"
                }
            }
        },
        "proxyapi.ChatCompletionResponseFormat": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                }
            }
        },
        "proxyapi.ChatMessageImageURL": {
            "type": "object",
            "properties": {
                "detail": {
                    "$ref": "#/definitions/proxyapi.ImageURLDetail"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "proxyapi.ChatMessagePart": {
            "type": "object",
            "properties": {
                "image_url": {
                    "$ref": "#/definitions/proxyapi.ChatMessageImageURL"
                },
                "text": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/proxyapi.ChatMessagePartType"
                }
            }
        },
        "proxyapi.ChatMessagePartType": {
            "type": "string",
            "enum": [
                "text",
                "image_url"
            ],
            "x-enum-varnames": [
                "ChatMessagePartTypeText",
                "ChatMessagePartTypeImageURL"
            ]
        },
        "proxyapi.FinishReason": {
            "type": "string",
            "enum": [
                "stop"
            ],
            "x-enum-varnames": [
                "FinishReasonStop"
            ]
        },
        "proxyapi.ImageURLDetail": {
            "type": "string",
            "enum": [
                "high",
                "low",
                "auto"
            ],
            "x-enum-varnames": [
                "ImageURLDetailHigh",
                "ImageURLDetailLow",
                "ImageURLDetailAuto"
            ]
        },
        "proxyapi.InitiateSessionReq": {
            "type": "object",
            "required": [
                "bidId",
                "provider",
                "providerUrl",
                "spend",
                "user"
            ],
            "properties": {
                "bidId": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "providerUrl": {
                    "type": "string"
                },
                "spend": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "proxyapi.LogProb": {
            "type": "object",
            "properties": {
                "bytes": {
                    "description": "Omitting the field if it is null",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "logprob": {
                    "type": "number"
                },
                "token": {
                    "type": "string"
                },
                "top_logprobs": {
                    "description": "TopLogProbs is a list of the most likely tokens and their log probability, at this token position.\nIn rare cases, there may be fewer than the number of requested top_logprobs returned.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/proxyapi.TopLogProbs"
                    }
                }
            }
        },
        "proxyapi.LogProbs": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Content is a list of message content tokens with log probability information.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/proxyapi.LogProb"
                    }
                }
            }
        },
        "proxyapi.OpenAiCompletitionRequest": {
            "type": "object",
            "properties": {
                "frequency_penalty": {
                    "type": "number"
                },
                "function_call": {
                    "description": "Deprecated: use ToolChoice instead."
                },
                "logit_bias": {
                    "description": "LogitBias is must be a token id string (specified by their token ID in the tokenizer), not a word string.\nincorrect: ` + "`" + `\"logit_bias\":{\"You\": 6}` + "`" + `, correct: ` + "`" + `\"logit_bias\":{\"1639\": 6}` + "`" + `\nrefs: https://platform.openai.com/docs/api-reference/chat/create#chat/create-logit_bias",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "logprobs": {
                    "description": "LogProbs indicates whether to return log probabilities of the output tokens or not.\nIf true, returns the log probabilities of each output token returned in the content of message.\nThis option is currently not available on the gpt-4-vision-preview model.",
                    "type": "boolean"
                },
                "max_tokens": {
                    "type": "integer"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/proxyapi.ChatCompletionMessage"
                    }
                },
                "model": {
                    "type": "string"
                },
                "n": {
                    "type": "integer"
                },
                "presence_penalty": {
                    "type": "number"
                },
                "response_format": {
                    "$ref": "#/definitions/proxyapi.ChatCompletionResponseFormat"
                },
                "seed": {
                    "type": "integer"
                },
                "stop": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "stream": {
                    "type": "boolean"
                },
                "temperature": {
                    "type": "number"
                },
                "tool_choice": {
                    "description": "This can be either a string or an ToolChoice object."
                },
                "top_logprobs": {
                    "description": "TopLogProbs is an integer between 0 and 5 specifying the number of most likely tokens to return at each\ntoken position, each with an associated log probability.\nlogprobs must be set to true if this parameter is used.",
                    "type": "integer"
                },
                "top_p": {
                    "type": "number"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "proxyapi.TopLogProbs": {
            "type": "object",
            "properties": {
                "bytes": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "logprob": {
                    "type": "number"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "proxyapi.Usage": {
            "type": "object",
            "properties": {
                "completion_tokens": {
                    "type": "integer"
                },
                "prompt_tokens": {
                    "type": "integer"
                },
                "total_tokens": {
                    "type": "integer"
                }
            }
        },
        "structs.AllowanceRes": {
            "type": "object",
            "properties": {
                "allowance": {
                    "type": "string",
                    "example": "100000000"
                }
            }
        },
        "structs.AmountReq": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "string"
                }
            }
        },
        "structs.BalanceRes": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "string"
                }
            }
        },
        "structs.Bid": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "modelAgentId": {
                    "type": "string"
                },
                "nonce": {
                    "type": "string"
                },
                "pricePerSecond": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "structs.BidRes": {
            "type": "object",
            "properties": {
                "bid": {
                    "$ref": "#/definitions/structs.Bid"
                }
            }
        },
        "structs.BidsRes": {
            "type": "object",
            "properties": {
                "bids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/structs.Bid"
                    }
                }
            }
        },
        "structs.BlockRes": {
            "type": "object",
            "properties": {
                "block": {
                    "type": "integer",
                    "example": 1234
                }
            }
        },
        "structs.BudgetRes": {
            "type": "object",
            "properties": {
                "budget": {
                    "type": "string",
                    "example": "100000000"
                }
            }
        },
        "structs.CreateBidRequest": {
            "type": "object",
            "required": [
                "modelID",
                "pricePerSecond"
            ],
            "properties": {
                "modelID": {
                    "type": "string"
                },
                "pricePerSecond": {
                    "type": "string"
                }
            }
        },
        "structs.CreateModelRequest": {
            "type": "object",
            "required": [
                "fee",
                "ipfsID",
                "name",
                "stake",
                "tags"
            ],
            "properties": {
                "fee": {
                    "type": "string",
                    "example": "123000000000"
                },
                "id": {
                    "type": "string",
                    "example": "0x1234"
                },
                "ipfsID": {
                    "type": "string",
                    "example": "0x1234"
                },
                "name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1,
                    "example": "Llama 2.0"
                },
                "stake": {
                    "type": "string",
                    "example": "123000000000"
                },
                "tags": {
                    "type": "array",
                    "maxItems": 64,
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "structs.CreateProviderRequest": {
            "type": "object",
            "required": [
                "endpoint",
                "stake"
            ],
            "properties": {
                "endpoint": {
                    "type": "string",
                    "example": "mycoolmornode.domain.com:3989"
                },
                "stake": {
                    "type": "string",
                    "example": "123000000000"
                }
            }
        },
        "structs.Model": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "fee": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ipfsCID": {
                    "type": "string"
                },
                "isDeleted": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "stake": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "structs.ModelRes": {
            "type": "object",
            "properties": {
                "model": {
                    "$ref": "#/definitions/structs.Model"
                }
            }
        },
        "structs.ModelsRes": {
            "type": "object",
            "properties": {
                "models": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/structs.Model"
                    }
                }
            }
        },
        "structs.OpenSessionRequest": {
            "type": "object",
            "required": [
                "approval",
                "approvalSig",
                "stake"
            ],
            "properties": {
                "approval": {
                    "type": "string",
                    "format": "hex",
                    "example": "0x1234"
                },
                "approvalSig": {
                    "type": "string",
                    "format": "hex",
                    "example": "0x1234"
                },
                "stake": {
                    "type": "string",
                    "example": "123000000000"
                }
            }
        },
        "structs.OpenSessionRes": {
            "type": "object",
            "properties": {
                "sessionID": {
                    "type": "string",
                    "example": "0x1234"
                }
            }
        },
        "structs.OpenSessionWithDurationRequest": {
            "type": "object",
            "properties": {
                "sessionDuration": {
                    "type": "string"
                }
            }
        },
        "structs.Provider": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "isDeleted": {
                    "type": "boolean"
                },
                "stake": {
                    "type": "string"
                }
            }
        },
        "structs.ProviderRes": {
            "type": "object",
            "properties": {
                "provider": {
                    "$ref": "#/definitions/structs.Provider"
                }
            }
        },
        "structs.ProvidersRes": {
            "type": "object",
            "properties": {
                "providers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/structs.Provider"
                    }
                }
            }
        },
        "structs.RawTransaction": {
            "type": "object",
            "properties": {
                "blockHash": {
                    "type": "string"
                },
                "blockNumber": {
                    "type": "string"
                },
                "confirmations": {
                    "type": "string"
                },
                "contractAddress": {
                    "type": "string"
                },
                "cumulativeGasUsed": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "functionName": {
                    "type": "string"
                },
                "gas": {
                    "type": "string"
                },
                "gasPrice": {
                    "type": "string"
                },
                "gasPriceBid": {
                    "type": "string"
                },
                "gasUsed": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "input": {
                    "type": "string"
                },
                "isError": {
                    "type": "string"
                },
                "methodId": {
                    "type": "string"
                },
                "nonce": {
                    "type": "string"
                },
                "timeStamp": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "transactionIndex": {
                    "type": "string"
                },
                "txreceipt_status": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "structs.ScoredBid": {
            "type": "object",
            "properties": {
                "bid": {
                    "$ref": "#/definitions/structs.Bid"
                },
                "id": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                }
            }
        },
        "structs.ScoredBidsRes": {
            "type": "object",
            "properties": {
                "bids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/structs.ScoredBid"
                    }
                }
            }
        },
        "structs.SendRequest": {
            "type": "object",
            "required": [
                "amount",
                "to"
            ],
            "properties": {
                "amount": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "structs.Session": {
            "type": "object",
            "properties": {
                "bidID": {
                    "type": "string"
                },
                "closedAt": {
                    "type": "string"
                },
                "closeoutReceipt": {
                    "type": "string"
                },
                "closeoutType": {
                    "type": "string"
                },
                "endsAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "modelAgentId": {
                    "type": "string"
                },
                "openedAt": {
                    "type": "string"
                },
                "pricePerSecond": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "providerWithdrawnAmount": {
                    "type": "string"
                },
                "stake": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "structs.SessionRes": {
            "type": "object",
            "properties": {
                "session": {
                    "$ref": "#/definitions/structs.Session"
                }
            }
        },
        "structs.SessionsRes": {
            "type": "object",
            "properties": {
                "sessions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/structs.Session"
                    }
                }
            }
        },
        "structs.SupplyRes": {
            "type": "object",
            "properties": {
                "supply": {
                    "type": "string",
                    "example": "100000000"
                }
            }
        },
        "structs.TokenBalanceRes": {
            "type": "object",
            "properties": {
                "eth": {
                    "type": "string",
                    "example": "100000000"
                },
                "mor": {
                    "type": "string",
                    "example": "100000000"
                }
            }
        },
        "structs.TransactionsRes": {
            "type": "object",
            "properties": {
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/structs.RawTransaction"
                    }
                }
            }
        },
        "structs.TxRes": {
            "type": "object",
            "properties": {
                "tx": {
                    "type": "string",
                    "example": "0x1234"
                }
            }
        },
        "system.ConfigResponse": {
            "type": "object",
            "properties": {
                "commit": {
                    "type": "string"
                },
                "config": {},
                "derivedConfig": {},
                "version": {
                    "type": "string"
                }
            }
        },
        "system.FD": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "system.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "walletapi.SetupWalletReqBody": {
            "type": "object",
            "required": [
                "privateKey"
            ],
            "properties": {
                "privateKey": {
                    "type": "string"
                }
            }
        },
        "walletapi.WalletRes": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0x1234"
                }
            }
        },
        "walletapi.statusRes": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Morpheus Lumerin Node API",
	Description:      "API for Morpheus Lumerin Node",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
