// Arm r1_t5_nosend: SPEC-R1-R3.md R2 rendezvous (KK3) / R1-T5 (unprivileged
// part): the rendezvous deadline covers both the connection and the byte — a
// child that connects but sends nothing must be refused with
// SEALED_SPAWN_RENDEZVOUS at the deadline, the call returns instead of
// hanging, and the child is reaped. Expressed through the module: the child is
// pinned by its own CD hash, with requirement bytes naming its own hash
// (generated at run time by the reqgen tool the Makefile builds from
// a13.swift, dumpfile route — it exits before launching anything), so it
// passes the pre-resume verification, is resumed, writes its marker, connects
// to $TMPDIR/rv, and then stays silent. Positive control in the same program:
// the pinned child-ok with the shipping requirement bytes is accepted (OK)
// and runs to its marker. SKIP if the module refuses the spec (no usable
// requirement bytes for this child).
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include "harness.h"

static char why[256];

static int hex_of(const char *child, const char *envh, char out[64]) {
    if (envh != NULL && strlen(envh) == 2 * SEALED_CDHASH_LEN) {
        snprintf(out, 64, "%s", envh);
        return 0;
    }
    char cmd[1200];
    snprintf(cmd, sizeof cmd, "codesign -dvvv '%s' 2>&1", child);
    FILE *f = popen(cmd, "r");
    if (f == NULL) return 1;
    char line[512], hex[64];
    int ok = 1;
    while (fgets(line, sizeof line, f) != NULL) {
        char *p = strstr(line, "CDHash=");
        if (p != NULL) {
            p += 7;
            char *e = strchr(p, '\n');
            if (e != NULL) *e = '\0';
            if (strlen(p) == 2 * SEALED_CDHASH_LEN) {
                snprintf(hex, sizeof hex, "%s", p);
                ok = 0;
            }
        }
    }
    pclose(f);
    if (ok) return 1;
    snprintf(out, 64, "%s", hex);
    return 0;
}

static double now_ms(void) {
    struct timespec t;
    if (clock_gettime(CLOCK_MONOTONIC, &t) != 0) return 0.0;
    return t.tv_sec * 1000.0 + t.tv_nsec / 1e6;
}

// Requirement bytes naming the child's own CD hash, generated by reqgen
// (a13.swift dumpfile route; it exits before launching the child).
static int gen_req(const char *work, const char *child, const char *hash, const char *out) {
    char cmd[1600];
    snprintf(cmd, sizeof cmd, "'%s/reqgen' '%s' '%s' dummy '%s' >/dev/null 2>&1",
             work, child, hash, out);
    if (system(cmd) != 0) return 1;
    return access(out, R_OK) != 0;
}

int main(void) {
    arm_begin("r1_t5_nosend");
    const char *ok = arm_env("CHILD_OK");
    const char *nosend = arm_env("CHILD_NOSEND");
    const char *req = arm_env("REQ_OK");
    const char *work = arm_env("WORKDIR");
    if (ok == NULL || nosend == NULL || req == NULL || work == NULL)
        arm_fail("R1-T5: env missing (CHILD_OK/CHILD_NOSEND/REQ_OK/WORKDIR)");
    char pin_ok[64], pin_ns[64];
    if (hex_of(ok, arm_env("HASH_OK"), pin_ok) != 0)
        arm_fail("R1-T5: could not get child-ok's CD hash (env HASH_OK and codesign both failed)");
    if (hex_of(nosend, NULL, pin_ns) != 0)
        arm_fail("R1-T5: could not get child-nosend's CD hash via codesign");

    char ctrl[512], ref[512], req_ns[600];
    snprintf(ctrl, sizeof ctrl, "%s/m.ctrl-ns", work);
    snprintf(ref, sizeof ref, "%s/m.ref-ns", work);
    snprintf(req_ns, sizeof req_ns, "%s/req-ns.bin", work);
    const char *ref_req = req_ns;
    if (req != NULL && gen_req(work, nosend, pin_ns, req_ns) != 0)
        ref_req = NULL;   // reqgen unusable: fall back to a requirement-less spec

    // Positive control: shipping shape, pinned child accepted.
    unlink(ctrl);
    sealed_child_spec_t spec;
    sealed_child_t st;
    if (arm_build_spec(&spec, ok, pin_ok, req, ctrl, 5000) != 0)
        arm_fail("R1-T5: control spec could not be built (bad pin hex or req bytes)");
    int rc = arm_spawn(&spec, &st);
    if (rc != SEALED_SPAWN_OK) {
        snprintf(why, sizeof why, "R1-T5: pinned control child refused: result=%s(%d)",
                 arm_code_name(rc), rc);
        arm_fail(why);
    }
    if (!arm_marker_written(ctrl)) {
        arm_fail("R1-T5: control accepted (OK) but the child never wrote its marker");
    }
    sealed_child_kill(&st);

    // Child that connects but sends nothing: RENDEZVOUS at the deadline.
    unlink(ref);
    if (arm_build_spec(&spec, nosend, pin_ns, ref_req, ref, 5000) != 0)
        arm_fail("R1-T5: refusal spec could not be built");
    double t0 = now_ms();
    rc = arm_spawn(&spec, &st);
    double ms = now_ms() - t0;
    if (rc == SEALED_SPAWN_REQUIREMENT)
        arm_skip("module refuses a spec with no launch requirement and no reqgen "
                 "bytes could be generated for the silent child");
    if (rc != SEALED_SPAWN_RENDEZVOUS) {
        snprintf(why, sizeof why, "R1-T5: expected RENDEZVOUS(%d) for a child that "
                 "sends no first byte, got %s(%d)", SEALED_SPAWN_RENDEZVOUS, arm_code_name(rc), rc);
        arm_fail(why);
    }
    if (st.reaped != 1) {
        arm_fail("R1-T5: refused but the child was not reaped");
    }
    if (!arm_marker_written(ref)) {
        arm_fail("R1-T5: the child never ran (marker missing) — nothing was tested");
    }
    if (ms > 15000.0) {
        snprintf(why, sizeof why, "R1-T5: call returned after %.0f ms — past the "
                 "rendezvous deadline (hang?)", ms);
        arm_fail(why);
    }
    snprintf(why, sizeof why, "R1-T5: connected but no first byte within the deadline "
             "refused with RENDEZVOUS, reaped, returned in %.0f ms (deadline 5000); "
             "control accepted", ms);
    arm_pass(why);
    return 0;
}
