// Arm r1_t5_crash_before_rv: SPEC-R1-R3.md R1-T5 (unprivileged part): a child
// that dies before the rendezvous is handled by the spawn-time port path —
// "the engine kills the child ... the child is reaped by its lifecycle state
// within a bounded time ... and the engine's handler deallocated the rights it
// received without using them". Expressed unprivileged through the module: the
// child is pinned by its own CD hash, with requirement bytes naming its own
// hash (generated at run time by the reqgen tool the Makefile builds from
// a13.swift, dumpfile route — it exits before launching anything), so it
// passes the pre-resume verification, is resumed, writes its marker, then
// faults before touching $TMPDIR/rv. Expected: SEALED_SPAWN_DIED ("the child
// died or raised an exception before verification"), reaped == 1, marker
// written (it ran), and sealed_spawn_child returns well inside the rendezvous
// deadline instead of hanging. Positive control in the same program: the
// pinned child-ok with the shipping requirement bytes is accepted (OK) and
// runs to its marker. SKIP if the module refuses the spec (no usable
// requirement bytes for this child).
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include "harness.h"

static char why[256];

static int hex_of(const char *child, const char *envh, char out[64]) {
    if (envh != NULL && strlen(envh) == 2 * SEALED_CDHASH_LEN) {
        snprintf(out, 64, "%s", envh);
        return 0;
    }
    char cmd[1200];
    snprintf(cmd, sizeof cmd, "codesign -dvvv '%s' 2>&1", child);
    FILE *f = popen(cmd, "r");
    if (f == NULL) return 1;
    char line[512], hex[64];
    int ok = 1;
    while (fgets(line, sizeof line, f) != NULL) {
        char *p = strstr(line, "CDHash=");
        if (p != NULL) {
            p += 7;
            char *e = strchr(p, '\n');
            if (e != NULL) *e = '\0';
            if (strlen(p) == 2 * SEALED_CDHASH_LEN) {
                snprintf(hex, sizeof hex, "%s", p);
                ok = 0;
            }
        }
    }
    pclose(f);
    if (ok) return 1;
    snprintf(out, 64, "%s", hex);
    return 0;
}

static double now_ms(void) {
    struct timespec t;
    if (clock_gettime(CLOCK_MONOTONIC, &t) != 0) return 0.0;
    return t.tv_sec * 1000.0 + t.tv_nsec / 1e6;
}

// Requirement bytes naming the child's own CD hash, generated by reqgen
// (a13.swift dumpfile route; it exits before launching the child).
static int gen_req(const char *work, const char *child, const char *hash, const char *out) {
    char cmd[1600];
    snprintf(cmd, sizeof cmd, "'%s/reqgen' '%s' '%s' dummy '%s' >/dev/null 2>&1",
             work, child, hash, out);
    if (system(cmd) != 0) return 1;
    return access(out, R_OK) != 0;
}

int main(void) {
    arm_begin("r1_t5_crash_before_rv");
    const char *ok = arm_env("CHILD_OK");
    const char *crash = arm_env("CHILD_CRASH");
    const char *req = arm_env("REQ_OK");
    const char *work = arm_env("WORKDIR");
    if (ok == NULL || crash == NULL || req == NULL || work == NULL)
        arm_fail("R1-T5: env missing (CHILD_OK/CHILD_CRASH/REQ_OK/WORKDIR)");
    char pin_ok[64], pin_crash[64];
    if (hex_of(ok, arm_env("HASH_OK"), pin_ok) != 0)
        arm_fail("R1-T5: could not get child-ok's CD hash (env HASH_OK and codesign both failed)");
    if (hex_of(crash, NULL, pin_crash) != 0)
        arm_fail("R1-T5: could not get child-crash's CD hash via codesign");

    char ctrl[512], ref[512], req_crash[600];
    snprintf(ctrl, sizeof ctrl, "%s/m.ctrl-crash", work);
    snprintf(ref, sizeof ref, "%s/m.ref-crash", work);
    snprintf(req_crash, sizeof req_crash, "%s/req-crash.bin", work);
    const char *ref_req = req_crash;
    if (req != NULL && gen_req(work, crash, pin_crash, req_crash) != 0)
        ref_req = NULL;   // reqgen unusable: fall back to a requirement-less spec

    // Positive control: shipping shape, pinned child accepted.
    unlink(ctrl);
    sealed_child_spec_t spec;
    sealed_child_t st;
    if (arm_build_spec(&spec, ok, pin_ok, req, ctrl, 5000) != 0)
        arm_fail("R1-T5: control spec could not be built (bad pin hex or req bytes)");
    int rc = arm_spawn(&spec, &st);
    if (rc != SEALED_SPAWN_OK) {
        snprintf(why, sizeof why, "R1-T5: pinned control child refused: result=%s(%d)",
                 arm_code_name(rc), rc);
        arm_fail(why);
    }
    if (!arm_marker_written(ctrl)) {
        arm_fail("R1-T5: control accepted (OK) but the child never wrote its marker");
    }
    double k0 = now_ms();
    sealed_child_kill(&st);
    printf("MEASURED kill r1_t5_crash_before_rv: %.0f ms\n", now_ms() - k0);
    // Crashing child: runs, faults before the rendezvous -> DIED, reaped, no hang.
    unlink(ref);
    if (arm_build_spec(&spec, crash, pin_crash, ref_req, ref, 5000) != 0)
        arm_fail("R1-T5: refusal spec could not be built");
    double t0 = now_ms();
    rc = arm_spawn(&spec, &st);
    double ms = now_ms() - t0;
    if (rc == SEALED_SPAWN_REQUIREMENT)
        arm_skip("module refuses a spec with no launch requirement and no reqgen "
                 "bytes could be generated for the crashing child");
    if (rc != SEALED_SPAWN_DIED) {
        snprintf(why, sizeof why, "R1-T5: expected DIED(%d) for a child that died "
                 "before the rendezvous, got %s(%d)", SEALED_SPAWN_DIED, arm_code_name(rc), rc);
        arm_fail(why);
    }
    if (st.reaped != 1) {
        arm_fail("R1-T5: refused but the child was not reaped by its lifecycle state");
    }
    if (!arm_marker_written(ref)) {
        arm_fail("R1-T5: the crashing child never ran (marker missing) — nothing was tested");
    }
    if (ms > 15000.0) {
        snprintf(why, sizeof why, "R1-T5: call returned after %.0f ms — past the "
                 "rendezvous deadline (hang?)", ms);
        arm_fail(why);
    }
    snprintf(why, sizeof why, "R1-T5: crash before rendezvous refused with DIED, "
             "reaped, returned in %.0f ms (deadline 5000); control accepted", ms);
    arm_pass(why);
    return 0;
}
