---
version: "2.0"
services:
  morpheus-lumerin-node:
    image: ghcr.io/morpheusais/morpheus-lumerin-node:v3.0.0
    expose:
      - port: 8082
        as: 8082
        to:
          - global: true
      - port: 3333
        as: 3333
        proto: tcp
        to:
          - global: true
    env:
      - COOKIE_CONTENT=admin:superpassword
      - WALLET_PRIVATE_KEY=
      - WEB_PUBLIC_URL=http://localhost:8082
      - WEB_ADDRESS=0.0.0.0:8082
      - PROXY_ADDRESS=0.0.0.0:3333
      - >-
        MODELS_CONFIG_CONTENT={
          "$schema": "https://raw.githubusercontent.com/MorpheusAIs/Morpheus-Lumerin-Node/v3.0.0/proxy-router/internal/config/models-config-schema.json",
          "models": [
            {
              "modelId": "<MODEL_ID>",
              "modelName": "<MODEL_NAME",
              "apiType": "openai",
              "apiUrl": "<http://llmprovider.dns_or_ip:port>",
              "concurrentSlots": 8,
              "capacityPolicy": "simple"
            }
          ]
        }
      - ETH_NODE_CHAIN_ID=8453
      - DIAMOND_CONTRACT_ADDRESS=0x6aBE1d282f72B474E54527D93b979A4f64d3030a
      - MOR_TOKEN_ADDRESS=0x7431aDa8a591C955a994a21710752EF9b882b8e3
      - BLOCKSCOUT_API_URL=https://base.blockscout.com/api/v2
profiles:
  compute:
    morpheus-lumerin-node:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
  placement:
    dcloud:
      pricing:
        morpheus-lumerin-node:
          denom: uakt
          amount: 10000
deployment:
  morpheus-lumerin-node:
    dcloud:
      profile: morpheus-lumerin-node
      count: 1
