---
version: "2.0"
services:
  proxy-router:
    image: ghcr.io/lumerin-protocol/morpheus-lumerin-node:v2.2.50-dev
    expose:
      - port: 8082
        as: 8082
        to:
          - global: true
      - port: 3333
        as: 3333
        proto: tcp
        to:
          - global: true
    env:
      - WALLET_PRIVATE_KEY=
      - COOKIE_CONTENT=admin:password
      - MODELS_CONFIG_CONTENT={"$schema":"./internal/config/models-config-schema.json","models":[{"modelId":"0x0000000000000000000000000000000000000000000000000000000000000000","modelName":"llama2","apiType":"openai","apiUrl":"http://localhost:8080/v1"},{"modelId":"0x0000000000000000000000000000000000000000000000000000000000000001","modelName":"inference.sdxl.txt2img.v1","apiType":"prodia-v2","apiUrl":"https://inference.prodia.com/v2","apiKey":"FILL_ME_IN"}]}
      - ETH_NODE_CHAIN_ID=42161
      - BLOCKSCOUT_API_URL=https://arbitrum.blockscout.com/api/v2
      - DIAMOND_CONTRACT_ADDRESS=0xDE819AaEE474626E3f34Ef0263373357e5a6C71b
      - MOR_TOKEN_ADDRESS=0x092bAaDB7DEf4C3981454dD9c0A0D7FF07bCFc86
      - PROXY_ADDRESS=0.0.0.0:3333
      - WEB_ADDRESS=0.0.0.0:8082
      - WEB_PUBLIC_URL=http://localhost:8082
      - PROXY_STORE_CHAT_CONTEXT=false
      - LOG_COLOR=true
      - LOG_LEVEL_APP=info
      - LOG_LEVEL_TCP=info
      - LOG_LEVEL_ETH_RPC=info
      - LOG_LEVEL_STORAGE=info
profiles:
  compute:
    proxy-router:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
  placement:
    akash:
      pricing:
        proxy-router:
          denom: uakt
          amount: 10000
deployment:
  proxy-router:
    akash:
      profile: proxy-router
      count: 1
